# Emmerich Contaminats Detection Configurations
# github.com/rayandrews
# <raydreww@gmail.com>

[general]
name                         = "Emmerich Contaminants Detection"
debug                        = false # will log all debugging things

[image]
database                     = "contaminants.db"
directory                    = "images"

[camera]
index                        = 0

[modbus]
port                         = 1502

#----------------------------------------------------------------
# Modbus Data Mapping
#----------------------------------------------------------------
[modbus.data-mapping]

#----------------------------------------------------------------
# Coils
#
# Status from PLC to Jetson
#----------------------------------------------------------------
[modbus.data-mapping.coils]
starting-address             = 1
capacity                     = 10

[modbus.data-mapping.coils.data]
[modbus.data-mapping.coils.data.heartbeat]
address                      = 1
type                         = "byte"

[modbus.data-mapping.coils.data.imaging-request]
address                      = 2
type                         = "byte"

#----------------------------------------------------------------
# Discrete Inputs
#
# Status from Jetson to PLC
#----------------------------------------------------------------
[modbus.data-mapping.discrete-inputs]
starting-address             = 1
capacity                     = 10

[modbus.data-mapping.discrete-inputs.data]
[modbus.data-mapping.discrete-inputs.data.heartbeat]
address                      = 1
type                         = "byte"

[modbus.data-mapping.discrete-inputs.data.imaging-ready]
address                      = 2
type                         = "byte"

[modbus.data-mapping.discrete-inputs.data.imaging-done]
address                      = 3
type                         = "byte"

#----------------------------------------------------------------
# Input Registers
#
# Data from Jetson to PLC
#----------------------------------------------------------------
[modbus.data-mapping.input-registers]
starting-address             = 1
capacity                     = 20

[modbus.data-mapping.input-registers.data]
[modbus.data-mapping.input-registers.data.year]
address                      = 1
type                         = "word"
length                       = 1

[modbus.data-mapping.input-registers.data.month]
address                      = 2
type                         = "word"
length                       = 1

[modbus.data-mapping.input-registers.data.day]
address                      = 3
type                         = "word"
length                       = 1

[modbus.data-mapping.input-registers.data.hour]
address                      = 4
type                         = "word"
length                       = 1

[modbus.data-mapping.input-registers.data.minute]
address                      = 5
type                         = "word"
length                       = 1

[modbus.data-mapping.input-registers.data.second]
address                      = 6
type                         = "word"
length                       = 1

#----------------------------------------------------------------
# Holding Registers
#
# Data from PLC to Jetson
#----------------------------------------------------------------
[modbus.data-mapping.holding-registers]
starting-address             = 1
capacity                     = 20

[modbus.data-mapping.holding-registers.data]
[modbus.data-mapping.holding-registers.data.year]
address                      = 1
type                         = "word"
length                       = 1

[modbus.data-mapping.holding-registers.data.month]
address                      = 2
type                         = "word"
length                       = 1

[modbus.data-mapping.holding-registers.data.day]
address                      = 3
type                         = "word"
length                       = 1

[modbus.data-mapping.holding-registers.data.hour]
address                      = 4
type                         = "word"
length                       = 1

[modbus.data-mapping.holding-registers.data.minute]
address                      = 5
type                         = "word"
length                       = 1

[modbus.data-mapping.holding-registers.data.second]
address                      = 6
type                         = "word"
length                       = 1

[modbus.data-mapping.holding-registers.data.sku-card-instruction]
address                      = 7
type                         = "word"
length                       = 1

[modbus.data-mapping.holding-registers.data.sku-number]
address                      = 8
type                         = "word"
length                       = 1

[modbus.data-mapping.holding-registers.data.sku-production-day]
address                      = 9
type                         = "word"
length                       = 1

[modbus.data-mapping.holding-registers.data.tray-barcode]
address                      = 10
type                         = "dword"
length                       = 2

[modbus.data-mapping.holding-registers.data.lid-barcode]
address                      = 12
type                         = "dword"
length                       = 2

[modbus.data-mapping.holding-registers.data.batch-id]
address                      = 14
type                         = "dword"
length                       = 2

[modbus.data-mapping.holding-registers.data.infection-id]
address                      = 16
type                         = "dword"
length                       = 2
